package io.codepilot.core.graph.actions;

import com.alibaba.cloud.ai.graph.OverAllState;
import com.alibaba.cloud.ai.graph.action.NodeAction;
import io.codepilot.core.conversation.ToolResultBus;
import io.codepilot.core.dto.Patch;
import io.codepilot.core.graph.GraphSseHelper;
import io.codepilot.core.sse.SseEvents;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import java.time.Duration;
import java.util.*;

/**
 * ApplyPatch node: emits tool_call SSE for client-side patch execution,
 * awaits result via ToolResultBus (Redis Pub/Sub), then routes based on result.
 *
 * Flow:
 * 1. Extract patches from graph state (generated by GenerateAction)
 * 2. Optionally call ShadowWorkspace.validate() for pre-apply verification
 * 3. Emit tool_call SSE event to client for each patch
 * 4. Await tool results via ToolResultBus with timeout
 * 5. Collect results and route: success→verify, partial→verify with warnings, fail→repair
 */
@Component
public class ApplyPatchAction implements NodeAction {
    private static final Logger log = LoggerFactory.getLogger(ApplyPatchAction.class);

    private final ToolResultBus toolResultBus;
    private final ShadowVerifyHelper shadowHelper;

    public ApplyPatchAction(ToolResultBus toolResultBus, ShadowVerifyHelper shadowHelper) {
        this.toolResultBus = toolResultBus;
        this.shadowHelper = shadowHelper;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Map<String, Object> apply(OverAllState state) {
        var updates = new HashMap<String, Object>();
        updates.put("currentNode", "applyPatch");

        String sessionId = (String) state.value("sessionId").orElse("");
        String phaseId = (String) state.value("phaseCursor").orElse("");
        var patches = (List<Patch>) state.value("pendingPatches").orElse(List.of());

        if (patches.isEmpty()) {
            log.warn("ApplyPatch: no pending patches in state, skipping");
            updates.put("patchResult", "skipped");
            updates.put("patchErrors", List.of());
            return updates;
        }

        // ── Shadow Workspace pre-apply validation (01-§3.22) ──
        List<Map<String, String>> patchSummary = new ArrayList<>();
        for (Patch p : patches) {
            for (Patch.Edit edit : p.patches()) {
                patchSummary.add(Map.of(
                    "path", edit.path() != null ? edit.path() : "",
                    "op", edit.op() != null ? edit.op().name().toLowerCase() : "replace",
                    "content", edit.newContent() != null ? edit.newContent().substring(0, Math.min(edit.newContent().length(), 2000)) : ""
                ));
            }
        }
        var shadowResult = shadowHelper.requestValidation(state, sessionId, patchSummary);
        if (!shadowResult.passed()) {
            // Shadow validation failed → route to repair with shadow errors
            log.warn("ApplyPatch: Shadow validation failed, routing to repair. Errors: {}",
                shadowResult.errors().size());
            updates.put("patchResult", "shadow_failed");
            updates.put("patchErrors", shadowResult.errors().stream()
                .map(e -> e.file() + ":" + e.line() + ": " + e.message())
                .toList());
            updates.put("shadowValidationErrors", shadowResult.errors());
            GraphSseHelper.emitEvent(state, SseEvents.GRAPH_PHASE_DONE,
                Map.of("phaseId", phaseId, "shadowValidation", "failed",
                    "errorCount", shadowResult.errors().size()));
            return updates;
        }

        // Emit tool_call SSE for each patch
        List<Map<String, Object>> toolResults = new ArrayList<>();
        List<String> errors = new ArrayList<>();
        int appliedCount = 0;
        int failedCount = 0;

        for (Patch patch : patches) {
          for (Patch.Edit edit : patch.patches()) {
            String toolCallId = UUID.randomUUID().toString();

            // Build tool call arguments from Patch.Edit fields
            var toolArgs = Map.<String, Object>of(
                "toolCallId", toolCallId,
                "tool", "fs.applyPatch",
                "args", Map.of(
                    "path", edit.path() != null ? edit.path() : "",
                    "op", edit.op() != null ? edit.op().name().toLowerCase() : "replace",
                    "newContent", edit.newContent() != null ? edit.newContent() : "",
                    "search", edit.search() != null ? edit.search() : "",
                    "replace", edit.replace() != null ? edit.replace() : ""
                )
            );

            // Emit tool_call SSE event
            GraphSseHelper.emitEvent(state, SseEvents.TOOL_CALL, toolArgs);

            // Await result from client via ToolResultBus
            try {
                var result = toolResultBus.subscribe(sessionId)
                    .filter(e -> e.toolCallId().equals(toolCallId))
                    .timeout(Duration.ofSeconds(120))
                    .blockFirst();

                if (result != null && result.ok()) {
                    appliedCount++;
                    toolResults.add(Map.of("toolCallId", toolCallId, "success", true, "path", edit.path() != null ? edit.path() : ""));
                } else {
                    failedCount++;
                    String errMsg = result != null ? result.errorMessage() : "Timeout waiting for tool result";
                    errors.add("Patch failed for " + (edit.path() != null ? edit.path() : "unknown") + ": " + errMsg);
                    toolResults.add(Map.of("toolCallId", toolCallId, "success", false, "path", edit.path() != null ? edit.path() : "", "error", errMsg));
                }
            } catch (Exception e) {
                failedCount++;
                String errMsg = "Tool result timeout/error: " + e.getMessage();
                errors.add("Patch timeout for " + (edit.path() != null ? edit.path() : "unknown") + ": " + errMsg);
                toolResults.add(Map.of("toolCallId", toolCallId, "success", false, "path", edit.path() != null ? edit.path() : "", "error", errMsg));
            }
          }
        }

        // Update state with results
        updates.put("patchResults", toolResults);
        updates.put("patchErrors", errors);
        updates.put("appliedCount", appliedCount);
        updates.put("failedCount", failedCount);

        // Determine result status for routing
        if (failedCount == 0) {
            updates.put("patchResult", "success");
        } else if (appliedCount > 0) {
            updates.put("patchResult", "partial");
        } else {
            updates.put("patchResult", "failed");
        }

        // Emit progress event
        GraphSseHelper.emitEvent(state, SseEvents.GRAPH_PHASE_DONE,
            Map.of("phaseId", phaseId, "applied", appliedCount, "failed", failedCount));

        log.info("ApplyPatch: {} applied, {} failed out of {} patches", appliedCount, failedCount, patches.size());
        return updates;
    }

    public String routeAfterApplyPatch(OverAllState state) {
        String result = (String) state.value("patchResult").orElse("failed");
        return switch (result) {
            case "success", "partial" -> "verify";
            case "skipped" -> "verify";
            case "shadow_failed" -> "repair";
            default -> "repair";
        };
    }
}