package io.codepilot.core.graph.actions;

import com.alibaba.cloud.ai.graph.OverAllState;
import com.alibaba.cloud.ai.graph.action.NodeAction;
import io.codepilot.core.conversation.ToolResultBus;
import io.codepilot.core.dto.Patch;
import io.codepilot.core.graph.GraphSseHelper;
import io.codepilot.core.sse.SseEvents;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import java.time.Duration;
import java.util.*;

/**
 * ApplyPatch node: emits tool_call SSE for client-side patch execution,
 * awaits result via ToolResultBus (Redis Pub/Sub), then routes based on result.
 *
 * <p>C2 optimization: Multiple patches are now batched into a single tool_call
 * to reduce N×RTT latency. Falls back to individual edits on batch failure.
 *
 * <p>Flow:
 * 1. Extract patches from graph state (generated by GenerateAction)
 * 2. Optionally call ShadowWorkspace.validate() for pre-apply verification
 * 3. Emit batch tool_call SSE event to client
 * 4. Await tool results via ToolResultBus with timeout
 * 5. On batch failure, fall back to individual edits for partial success
 * 6. Collect results and route: success→verify/commit, partial→verify/commit, fail→repair
 */
@Component
public class ApplyPatchAction implements NodeAction {
    private static final Logger log = LoggerFactory.getLogger(ApplyPatchAction.class);

    private final ToolResultBus toolResultBus;
    private final ShadowVerifyHelper shadowHelper;

    public ApplyPatchAction(ToolResultBus toolResultBus, ShadowVerifyHelper shadowHelper) {
        this.toolResultBus = toolResultBus;
        this.shadowHelper = shadowHelper;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Map<String, Object> apply(OverAllState state) {
        var updates = new HashMap<String, Object>();
        updates.put("currentNode", "applyPatch");

        String sessionId = (String) state.value("sessionId").orElse("");
        String phaseId = (String) state.value("phaseCursor").orElse("");
        var patches = (List<Patch>) state.value("pendingPatches").orElse(List.of());

        if (patches.isEmpty()) {
            log.warn("ApplyPatch: no pending patches in state, skipping");
            updates.put("patchResult", "skipped");
            updates.put("patchErrors", List.of());
            return updates;
        }

        // ── Shadow Workspace pre-apply validation (01-§3.22) ──
        long createCount = patches.stream()
                .flatMap(p -> p.patches().stream())
                .filter(e -> e.op() == Patch.Edit.Op.CREATE)
                .count();
        long totalEdits = patches.stream()
                .mapToLong(p -> p.patches().size())
                .sum();

        List<Map<String, String>> patchSummary = new ArrayList<>();
        if (createCount < totalEdits) {
            for (Patch p : patches) {
                for (Patch.Edit edit : p.patches()) {
                    if (edit.op() != Patch.Edit.Op.CREATE) {
                        patchSummary.add(Map.of(
                                "path", edit.path() != null ? edit.path() : "",
                                "op", edit.op() != null ? edit.op().name().toLowerCase() : "replace",
                                "content", edit.newContent() != null ? edit.newContent().substring(0, Math.min(edit.newContent().length(), 500)) : ""
                        ));
                    }
                }
            }
        }

        if (!patchSummary.isEmpty()) {
            var shadowResult = shadowHelper.requestValidation(state, sessionId, patchSummary);
            if (!shadowResult.passed()) {
                log.warn("ApplyPatch: Shadow validation failed, routing to repair. Errors: {}",
                        shadowResult.errors().size());
                updates.put("patchResult", "shadow_failed");
                updates.put("patchErrors", shadowResult.errors().stream()
                        .map(e -> e.file() + ":" + e.line() + ": " + e.message())
                        .toList());
                updates.put("shadowValidationErrors", shadowResult.errors());
                GraphSseHelper.emitEvent(state, SseEvents.GRAPH_PHASE_DONE,
                        Map.of("phaseId", phaseId, "shadowValidation", "failed",
                                "errorCount", shadowResult.errors().size()));
                return updates;
            }
        }

        // ── C2 fix: Batch all edits into a single tool_call for efficient execution ──
        List<Map<String, Object>> toolResults = new ArrayList<>();
        List<String> errors = new ArrayList<>();
        int appliedCount = 0;
        int failedCount = 0;

        // Collect all edits from all patches into a single batch
        List<Map<String, Object>> allEdits = new ArrayList<>();
        for (Patch patch : patches) {
            for (Patch.Edit edit : patch.patches()) {
                allEdits.add(Map.<String, Object>of(
                        "path", edit.path() != null ? edit.path() : "",
                        "op", edit.op() != null ? edit.op().name().toLowerCase() : "replace",
                        "newContent", edit.newContent() != null ? edit.newContent() : "",
                        "search", edit.search() != null ? edit.search() : "",
                        "replace", edit.replace() != null ? edit.replace() : ""
                ));
            }
        }

        if (!allEdits.isEmpty()) {
            String batchToolCallId = UUID.randomUUID().toString();

            // Build batch tool call arguments
            Map<String, Object> batchArgs;
            if (allEdits.size() == 1) {
                // Single edit: use the original single-edit format for backward compatibility
                var singleEdit = allEdits.get(0);
                batchArgs = Map.<String, Object>of(
                        "id", batchToolCallId,
                        "name", "fs.applyPatch",
                        "args", singleEdit
                );
            } else {
                // Multiple edits: use batch format
                batchArgs = Map.<String, Object>of(
                        "id", batchToolCallId,
                        "name", "fs.applyPatch",
                        "args", Map.of("patches", allEdits)
                );
            }

            // Emit batch tool_call SSE event
            GraphSseHelper.emitEvent(state, SseEvents.TOOL_CALL, batchArgs);

            // Await result from client via ToolResultBus
            try {
                var result = toolResultBus.subscribe(sessionId)
                        .filter(e -> e.toolCallId().equals(batchToolCallId))
                        .timeout(Duration.ofSeconds(120))
                        .blockFirst();

                if (result != null && result.ok()) {
                    appliedCount = allEdits.size();
                    for (var edit : allEdits) {
                        String path = (String) edit.get("path");
                        toolResults.add(Map.of("toolCallId", batchToolCallId, "success", true, "path", path != null ? path : ""));
                    }
                } else {
                    String errMsg = result != null ? result.errorMessage() : "Timeout waiting for tool result";
                    log.warn("Batch applyPatch failed, falling back to individual edits: {}", errMsg);
                    var individualResult = applyIndividualEdits(state, sessionId, patches);
                    toolResults.addAll(individualResult.toolResults());
                    errors.addAll(individualResult.errors());
                    appliedCount = individualResult.appliedCount();
                    failedCount = individualResult.failedCount();
                }
            } catch (Exception e) {
                String errMsg = "Batch tool result timeout: " + e.getMessage();
                log.warn("{}. Falling back to individual edits.", errMsg);
                var individualResult = applyIndividualEdits(state, sessionId, patches);
                toolResults.addAll(individualResult.toolResults());
                errors.addAll(individualResult.errors());
                appliedCount = individualResult.appliedCount();
                failedCount = individualResult.failedCount();
            }
        }

        // Update state with results
        updates.put("patchResults", toolResults);
        updates.put("patchErrors", errors);
        updates.put("appliedCount", appliedCount);
        updates.put("failedCount", failedCount);

        // Determine result status for routing
        if (failedCount == 0) {
            updates.put("patchResult", "success");
        } else if (appliedCount > 0) {
            updates.put("patchResult", "partial");
        } else {
            updates.put("patchResult", "failed");
        }

        // Emit progress event
        GraphSseHelper.emitEvent(state, SseEvents.GRAPH_PHASE_DONE,
                Map.of("phaseId", phaseId, "applied", appliedCount, "failed", failedCount));

        log.info("ApplyPatch: {} applied, {} failed out of {} patches", appliedCount, failedCount, patches.size());
        return updates;
    }

    public String routeAfterApplyPatch(OverAllState state) {
        String result = (String) state.value("patchResult").orElse("failed");

        // C1 fast-path: if policy allows, skip verify for simple tasks
        boolean fastPath = Boolean.TRUE.equals(state.value("fastPathEnabled").orElse(false));
        if (fastPath && ("success".equals(result) || "partial".equals(result))) {
            log.info("ApplyPatch fast-path: skipping verify, routing directly to commit");
            return "commit";
        }

        return switch (result) {
            case "success", "partial" -> "verify";
            case "skipped" -> "verify";
            case "shadow_failed" -> "repair";
            default -> "repair";
        };
    }

    // ─── Individual Edit Fallback (for batch failure) ────────────────

    /**
     * Fallback: apply patches one-by-one when the batch tool_call fails.
     * Preserves backward compatibility and allows partial success.
     */
    @SuppressWarnings("unchecked")
    private IndividualResult applyIndividualEdits(OverAllState state, String sessionId, List<Patch> patches) {
        List<Map<String, Object>> toolResults = new ArrayList<>();
        List<String> errors = new ArrayList<>();
        int appliedCount = 0;
        int failedCount = 0;

        for (Patch patch : patches) {
            for (Patch.Edit edit : patch.patches()) {
                String toolCallId = UUID.randomUUID().toString();
                var toolArgs = Map.<String, Object>of(
                        "id", toolCallId,
                        "name", "fs.applyPatch",
                        "args", Map.of(
                                "path", edit.path() != null ? edit.path() : "",
                                "op", edit.op() != null ? edit.op().name().toLowerCase() : "replace",
                                "newContent", edit.newContent() != null ? edit.newContent() : "",
                                "search", edit.search() != null ? edit.search() : "",
                                "replace", edit.replace() != null ? edit.replace() : ""
                        )
                );

                GraphSseHelper.emitEvent(state, SseEvents.TOOL_CALL, toolArgs);

                try {
                    var result = toolResultBus.subscribe(sessionId)
                            .filter(e -> e.toolCallId().equals(toolCallId))
                            .timeout(Duration.ofSeconds(60))
                            .blockFirst();

                    if (result != null && result.ok()) {
                        appliedCount++;
                        toolResults.add(Map.of("toolCallId", toolCallId, "success", true, "path", edit.path() != null ? edit.path() : ""));
                    } else {
                        failedCount++;
                        String errMsg = result != null ? result.errorMessage() : "Timeout";
                        errors.add("Patch failed for " + (edit.path() != null ? edit.path() : "unknown") + ": " + errMsg);
                        toolResults.add(Map.of("toolCallId", toolCallId, "success", false, "path", edit.path() != null ? edit.path() : "", "error", errMsg));
                    }
                } catch (Exception e) {
                    failedCount++;
                    errors.add("Patch timeout for " + (edit.path() != null ? edit.path() : "unknown") + ": " + e.getMessage());
                    toolResults.add(Map.of("toolCallId", toolCallId, "success", false, "path", edit.path() != null ? edit.path() : "", "error", e.getMessage()));
                }
            }
        }

        return new IndividualResult(toolResults, errors, appliedCount, failedCount);
    }

    private record IndividualResult(
            List<Map<String, Object>> toolResults,
            List<String> errors,
            int appliedCount,
            int failedCount) {}
}