package io.codepilot.core.graph.actions;

import com.alibaba.cloud.ai.graph.OverAllState;
import com.alibaba.cloud.ai.graph.action.NodeAction;
import io.codepilot.core.conversation.ToolResultBus;
import io.codepilot.core.conversation.ToolResultBus.ToolResultEvent;
import io.codepilot.core.dto.Patch;
import io.codepilot.core.graph.GraphPatchUiHelper;
import io.codepilot.core.graph.GraphExecutionLog;
import io.codepilot.core.graph.GraphSseHelper;
import io.codepilot.core.graph.GraphToolWaitHelper;
import io.codepilot.core.graph.GraphUiEmitter;
import io.codepilot.core.graph.SessionExecutionFacts;
import io.codepilot.core.graph.UserPlanProgressHelper;
import io.codepilot.core.sse.SseEvents;
import io.codepilot.core.run.GraphEngineProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import java.time.Duration;
import java.util.*;

/**
 * ApplyPatch node: emits tool_call SSE for client-side patch execution,
 * awaits result via ToolResultBus (Redis Pub/Sub), then routes based on result.
 *
 * <p>C2 optimization: Multiple patches are now batched into a single tool_call
 * to reduce N×RTT latency. Falls back to individual edits on batch failure.
 *
 * <p>Flow:
 * 1. Extract patches from graph state (generated by GenerateAction)
 * 2. Optionally call ShadowWorkspace.validate() for pre-apply verification
 * 3. Emit batch tool_call SSE event to client
 * 4. Await tool results via ToolResultBus with timeout
 * 5. On batch failure, fall back to individual edits for partial success
 * 6. Collect results and route: success→verify/commit, partial→verify/commit, fail→repair
 */
@Component
public class ApplyPatchAction implements NodeAction {
    private static final Logger log = LoggerFactory.getLogger(ApplyPatchAction.class);

    private final ToolResultBus toolResultBus;
    private final ShadowVerifyHelper shadowHelper;
    private final GraphEngineProperties graphProperties;

    public ApplyPatchAction(ToolResultBus toolResultBus, ShadowVerifyHelper shadowHelper,
                            GraphEngineProperties graphProperties) {
        this.toolResultBus = toolResultBus;
        this.shadowHelper = shadowHelper;
        this.graphProperties = graphProperties;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Map<String, Object> apply(OverAllState state) {
        var updates = new HashMap<String, Object>();
        updates.put("currentNode", "applyPatch");
        GraphExecutionLog.nodeEnter(state, "applyPatch");

        String sessionId = (String) state.value("sessionId").orElse("");
        String phaseId = (String) state.value("phaseCursor").orElse("");
        var patches = (List<Patch>) state.value("pendingPatches").orElse(List.of());

        if (patches.isEmpty()) {
            log.warn("ApplyPatch: no pending patches in state, skipping");
            updates.put("patchResult", "skipped");
            updates.put("patchErrors", List.of());
            return updates;
        }

        // ★ Filter out invalid patches: path must be a real file path (not "unknown"/blank),
        // and at least one of newContent/search/replace must be non-empty.
        List<Patch> validPatches = new ArrayList<>();
        for (Patch p : patches) {
            List<Patch.Edit> validEdits = new ArrayList<>();
            for (Patch.Edit edit : p.patches()) {
                String editPath = edit.path();
                boolean hasValidPath = editPath != null && !editPath.isBlank()
                        && !"unknown".equalsIgnoreCase(editPath);
                boolean hasContent = (edit.newContent() != null && !edit.newContent().isBlank())
                        || (edit.search() != null && !edit.search().isBlank())
                        || (edit.replace() != null && !edit.replace().isBlank());
                if (hasValidPath && hasContent) {
                    validEdits.add(edit);
                } else {
                    log.warn("ApplyPatch: filtering out invalid edit: path={}, op={}, hasContent={}",
                        editPath, edit.op(), hasContent);
                }
            }
            if (!validEdits.isEmpty()) {
                validPatches.add(new Patch(p.summary(), p.rationale(), validEdits,
                        p.diffSummary(), p.rollback(), p.followUps()));
            }
        }

        if (validPatches.isEmpty()) {
            log.warn("ApplyPatch: all patches were invalid (path=unknown/blank or empty content), skipping");
            updates.put("patchResult", "skipped");
            updates.put("patchErrors", List.of());
            return updates;
        }
        // Use validPatches instead of original patches from here on
        patches = validPatches;

        GraphUiEmitter.transition(state, "applyPatch");
        UserPlanProgressHelper.emitForCurrentPhase(state, "in_progress");

        // ── Shadow Workspace pre-apply validation (01-§3.22) ──
        long createCount = patches.stream()
                .flatMap(p -> p.patches().stream())
                .filter(e -> e.op() == Patch.Edit.Op.CREATE)
                .count();
        long totalEdits = patches.stream()
                .mapToLong(p -> p.patches().size())
                .sum();

        List<Map<String, String>> patchSummary = new ArrayList<>();
        if (createCount < totalEdits) {
            for (Patch p : patches) {
                for (Patch.Edit edit : p.patches()) {
                    if (edit.op() != Patch.Edit.Op.CREATE) {
                        patchSummary.add(Map.of(
                                "path", edit.path() != null ? edit.path() : "",
                                "op", edit.op() != null ? edit.op().name().toLowerCase() : "replace",
                                "content", edit.newContent() != null ? edit.newContent().substring(0, Math.min(edit.newContent().length(), 500)) : ""
                        ));
                    }
                }
            }
        }

        if (!patchSummary.isEmpty()) {
            var shadowResult = shadowHelper.requestValidation(state, sessionId, patchSummary);
            if (!shadowResult.passed()) {
                log.warn("ApplyPatch: Shadow validation failed, routing to repair. Errors: {}",
                        shadowResult.errors().size());
                updates.put("patchResult", "shadow_failed");
                updates.put("patchErrors", shadowResult.errors().stream()
                        .map(e -> e.file() + ":" + e.line() + ": " + e.message())
                        .toList());
                updates.put("shadowValidationErrors", shadowResult.errors());
                GraphSseHelper.emitEvent(state, SseEvents.GRAPH_PHASE_DONE,
                        Map.of("phaseId", phaseId, "shadowValidation", "failed",
                                "errorCount", shadowResult.errors().size()));
                return updates;
            }
        }

        // ── C2 fix: Batch all edits into a single tool_call for efficient execution ──
        List<Map<String, Object>> toolResults = new ArrayList<>();
        List<String> errors = new ArrayList<>();
        int appliedCount = 0;
        int failedCount = 0;

        // Collect all edits from all patches into a single batch
        List<Map<String, Object>> allEdits = new ArrayList<>();
        for (Patch patch : patches) {
            for (Patch.Edit edit : patch.patches()) {
                String path = edit.path() != null ? edit.path() : "";
                if (!SessionExecutionFacts.allowWrittenFileOverwrite(state)
                        && SessionExecutionFacts.isFileWritten(state, path)) {
                    log.warn("ApplyPatch: skipping already-written file {}", path);
                    continue;
                }
                allEdits.add(Map.<String, Object>of(
                        "path", path,
                        "op", edit.op() != null ? edit.op().name().toLowerCase() : "replace",
                        "newContent", edit.newContent() != null ? edit.newContent() : "",
                        "search", edit.search() != null ? edit.search() : "",
                        "replace", edit.replace() != null ? edit.replace() : ""
                ));
            }
        }

        if (allEdits.isEmpty()) {
            log.info("ApplyPatch: no edits left after dedup — treating as success");
            updates.put("patchResult", "success");
            updates.put("patchResults", List.of());
            updates.put("patchErrors", List.of());
            updates.put("appliedCount", 0);
            updates.put("failedCount", 0);
            GraphExecutionLog.nodeExit(state, "applyPatch", updates);
            return updates;
        }

        if (!allEdits.isEmpty()) {
            String batchToolCallId = UUID.randomUUID().toString();

            // Build batch tool call arguments
            Map<String, Object> batchArgs;
            if (allEdits.size() == 1) {
                // Single edit: use the original single-edit format for backward compatibility
                var singleEdit = allEdits.get(0);
                batchArgs = Map.<String, Object>of(
                        "id", batchToolCallId,
                        "name", "fs.applyPatch",
                        "args", singleEdit
                );
            } else {
                // Multiple edits: use batch format
                batchArgs = Map.<String, Object>of(
                        "id", batchToolCallId,
                        "name", "fs.applyPatch",
                        "args", Map.of("patches", allEdits)
                );
            }

            // Register future BEFORE emitting SSE to avoid race condition
            var pendingFuture = ToolResultBus.registerFuture(sessionId, batchToolCallId);

            List<Map<String, Object>> writingFiles = GraphPatchUiHelper.buildWritingFiles(patches);
            String writingText = GraphPatchUiHelper.buildWritingTextFromFiles(writingFiles);
            GraphSseHelper.emitEvent(state, SseEvents.AGENT_WRITING,
                Map.of("text", writingText, "files", writingFiles, "phaseId", phaseId));

            GraphExecutionLog.toolCallEmit(state, batchToolCallId, "fs.applyPatch", batchArgs);
            GraphSseHelper.emitEvent(state, SseEvents.TOOL_CALL, batchArgs);

            // Await result from client via ToolResultBus (CompletableFuture — primary path)
            try {
                ToolResultEvent result =
                        GraphToolWaitHelper.await(
                                pendingFuture, state, "应用补丁中", Duration.ofSeconds(120));

                if (result != null) {
                    GraphExecutionLog.toolResultAwait(
                            state, batchToolCallId, result.ok(), result.errorMessage());
                }
                if (patchApplySucceeded(result)) {
                    appliedCount = allEdits.size();
                    List<String> writtenPaths = new ArrayList<>();
                    for (var edit : allEdits) {
                        String path = (String) edit.get("path");
                        toolResults.add(Map.of("toolCallId", batchToolCallId, "success", true, "path", path != null ? path : ""));
                        if (path != null && !path.isBlank()) {
                            writtenPaths.add(path);
                        }
                    }
                    SessionExecutionFacts.recordWrittenFiles(state, updates, writtenPaths);
                    // ── Record change lineage for each written file ──

                    for (String writtenPath : writtenPaths) {
                        io.codepilot.core.memory.ChangeLineageTracker.recordChange(
                                state, updates, writtenPath, "",
                                "applyPatch in phase " + phaseId,
                                "", phaseId, 0);
                    }
                } else {
                    String errMsg = result != null ? result.errorMessage() : "Timeout waiting for tool result";
                    log.warn("Batch applyPatch failed, falling back to individual edits: {}", errMsg);
                    mergeIndividualFallback(state, updates, patches, sessionId, toolResults, errors);
                    appliedCount = countSuccessful(toolResults);
                    failedCount = errors.size();
                }
            } catch (Exception e) {
                ToolResultBus.unregisterFuture(sessionId, batchToolCallId);
                String errMsg = "Batch tool result timeout: " + e.getMessage();
                log.warn("{}. Falling back to individual edits.", errMsg);
                mergeIndividualFallback(state, updates, patches, sessionId, toolResults, errors);
                appliedCount = countSuccessful(toolResults);
                failedCount = errors.size();
            }
        }

        // Update state with results — use immutable copies to prevent ConcurrentModificationException
        // during state serialization/cloning by the graph framework
        updates.put("patchResults", List.copyOf(toolResults));
        updates.put("patchErrors", List.copyOf(errors));
        updates.put("appliedCount", appliedCount);
        updates.put("failedCount", failedCount);

        // Determine result status for routing
        if (failedCount == 0) {
            updates.put("patchResult", "success");
        } else if (appliedCount > 0) {
            updates.put("patchResult", "partial");
        } else {
            updates.put("patchResult", "failed");
        }

        // Fast-path: request quick IDE diagnostics (best-effort, non-blocking)
        // This is done in apply() rather than routeAfterApplyPatch() because
        // route functions should be side-effect-free.
        String patchResult = (String) updates.getOrDefault("patchResult", "failed");
        if (io.codepilot.core.graph.PhaseMemoryHelper.skipVerify(state)
                && ("success".equals(patchResult) || "partial".equals(patchResult))) {
            requestQuickDiagnostics(state);
        }

        // Emit progress event
        GraphSseHelper.emitEvent(state, SseEvents.GRAPH_PHASE_DONE,
                Map.of("phaseId", phaseId, "applied", appliedCount, "failed", failedCount));

        log.info("ApplyPatch: {} applied, {} failed out of {} patches", appliedCount, failedCount, patches.size());
        GraphExecutionLog.nodeExit(state, "applyPatch", updates);
        return updates;
    }

    /** Client may set ok=false while result body shows written=true — avoid double-apply fallback. */
    @SuppressWarnings("unchecked")
    private static boolean patchApplySucceeded(ToolResultEvent result) {
        if (result == null) {
            return false;
        }
        if (result.ok()) {
            return true;
        }
        Object body = result.result();
        if (!(body instanceof Map<?, ?> raw)) {
            return false;
        }
        Map<String, Object> m = (Map<String, Object>) raw;
        if (Boolean.TRUE.equals(m.get("written")) || Boolean.TRUE.equals(m.get("ok"))) {
            return true;
        }
        Object results = m.get("results");
        if (results instanceof List<?> list && !list.isEmpty()) {
            for (Object item : list) {
                if (item instanceof Map<?, ?> row) {
                    Map<String, Object> rowMap = (Map<String, Object>) row;
                    if (!Boolean.TRUE.equals(rowMap.get("written")) && !Boolean.TRUE.equals(rowMap.get("ok"))) {
                        return false;
                    }
                } else {
                    return false;
                }
            }
            return true;
        }
        return false;
    }

    public String routeAfterApplyPatch(OverAllState state) {
        String result = (String) state.value("patchResult").orElse("failed");

        // ★ Batch generation: after applying a batch, route back to generate
        // for the next batch instead of going to verify. The last batch
        // (hasMore=false) will go through normal verify→commit flow.
        if (Boolean.TRUE.equals(state.value("batchGenerationInProgress").orElse(false))
                && ("success".equals(result) || "partial".equals(result))) {
            // Check max passes — if exceeded, stop batch loop and go to verify
            int passes = (int) state.value("phaseGeneratePasses").orElse(0);
            int maxPasses = graphProperties.getMaxGeneratePassesPerPhase();
            if (passes >= maxPasses) {
                log.warn("ApplyPatch: batch generation hit max passes ({}), routing to verify instead of generate", passes);
                // Don't clear batchGenerationInProgress here — let verify/commit handle it
            } else {
                log.info("ApplyPatch: batch generation in progress, routing back to generate (pass {})", passes);
                return "generate";
            }
        }

        if (io.codepilot.core.graph.PhaseMemoryHelper.skipVerify(state)
                && ("success".equals(result) || "partial".equals(result))) {
            log.info("ApplyPatch: phase budget skipVerify=true, routing directly to commit");
            return "commit";
        }

        log.info("ApplyPatch routing: patchResult={}, routing to {}",
                result, switch (result) {
                    case "success", "partial" -> "verify";
                    case "skipped" -> "repair";   // All patches invalid → repair needed, not verify
                    case "shadow_failed" -> "repair";
                    default -> "repair";
                });

        return switch (result) {
            case "success", "partial" -> "verify";
            case "skipped" -> "repair";   // All patches invalid → repair needed, not verify
            case "shadow_failed" -> "repair";
            default -> "repair";
        };
    }

    /**
     * Best-effort request for IDE diagnostics in fast-path mode.
     * Unlike VerifyAction which blocks for diagnostics, this is fire-and-forget:
     * emits a tool_call and doesn't wait for the result. The diagnostics
     * will be available in state for the next turn if needed.
     */
    private void requestQuickDiagnostics(OverAllState state) {
        try {
            String sessionId = (String) state.value("sessionId").orElse("");
            @SuppressWarnings("unchecked")
            var modifiedFiles = (List<String>) state.value("modifiedFiles").orElse(List.of());
            if (modifiedFiles.isEmpty()) return;

            String diagToolCallId = UUID.randomUUID().toString();
            GraphSseHelper.emitEvent(state, SseEvents.TOOL_CALL, Map.of(
                    "id", diagToolCallId,
                    "name", "ide.diagnostics",
                    "args", Map.of("files", modifiedFiles, "fastPath", true)
            ));
            log.info("ApplyPatch fast-path: emitted quick diagnostics request for {} files", modifiedFiles.size());
        } catch (Exception e) {
            log.warn("ApplyPatch fast-path: quick diagnostics request failed (non-blocking): {}", e.getMessage());
        }
    }

    private static void mergeIndividualFallback(
            OverAllState state,
            Map<String, Object> updates,
            List<Patch> patches,
            String sessionId,
            List<Map<String, Object>> toolResults,
            List<String> errors) {
        IndividualResult individual = applyIndividualEdits(state, sessionId, patches);
        toolResults.addAll(individual.toolResults());
        errors.addAll(individual.errors());
        List<String> written = new ArrayList<>();
        for (Map<String, Object> tr : individual.toolResults()) {
            if (Boolean.TRUE.equals(tr.get("success"))) {
                Object path = tr.get("path");
                if (path != null && !path.toString().isBlank()) {
                    written.add(path.toString());
                }
            }
        }
        if (!written.isEmpty()) {
            SessionExecutionFacts.recordWrittenFiles(state, updates, written);
        }
    }

    private static int countSuccessful(List<Map<String, Object>> toolResults) {
        int n = 0;
        for (Map<String, Object> tr : toolResults) {
            if (Boolean.TRUE.equals(tr.get("success"))) {
                n++;
            }
        }
        return n;
    }

    // ─── Individual Edit Fallback (for batch failure) ────────────────

    /**
     * Fallback: apply patches one-by-one when the batch tool_call fails.
     * Preserves backward compatibility and allows partial success.
     */
    @SuppressWarnings("unchecked")
    private static IndividualResult applyIndividualEdits(OverAllState state, String sessionId, List<Patch> patches) {
        List<Map<String, Object>> toolResults = new ArrayList<>();
        List<String> errors = new ArrayList<>();
        int appliedCount = 0;
        int failedCount = 0;

        for (Patch patch : patches) {
            for (Patch.Edit edit : patch.patches()) {
                String path = edit.path() != null ? edit.path() : "";
                if (!SessionExecutionFacts.allowWrittenFileOverwrite(state)
                        && SessionExecutionFacts.isFileWritten(state, path)) {
                    log.warn("ApplyPatch individual: skipping already-written file {}", path);
                    continue;
                }
                String toolCallId = UUID.randomUUID().toString();
                var toolArgs = Map.<String, Object>of(
                        "id", toolCallId,
                        "name", "fs.applyPatch",
                        "args", Map.of(
                                "path", edit.path() != null ? edit.path() : "",
                                "op", edit.op() != null ? edit.op().name().toLowerCase() : "replace",
                                "newContent", edit.newContent() != null ? edit.newContent() : "",
                                "search", edit.search() != null ? edit.search() : "",
                                "replace", edit.replace() != null ? edit.replace() : ""
                        )
                );

                // Register future BEFORE emitting SSE to avoid race condition
                var editFuture = ToolResultBus.registerFuture(sessionId, toolCallId);
                GraphSseHelper.emitEvent(state, SseEvents.TOOL_CALL, toolArgs);

                try {
                    ToolResultEvent result =
                            GraphToolWaitHelper.await(
                                    editFuture, state, "应用补丁中", Duration.ofSeconds(60));

                    if (patchApplySucceeded(result)) {
                        appliedCount++;
                        toolResults.add(Map.of("toolCallId", toolCallId, "success", true, "path", path));
                    } else {
                        failedCount++;
                        String errMsg = result != null && result.errorMessage() != null ? result.errorMessage() : "Timeout";
                        errors.add("Patch failed for " + (edit.path() != null ? edit.path() : "unknown") + ": " + errMsg);
                        toolResults.add(Map.of("toolCallId", toolCallId, "success", false, "path", edit.path() != null ? edit.path() : "", "error", errMsg));
                    }
                } catch (Exception e) {
                    failedCount++;
                    String exMsg = e.getMessage() != null ? e.getMessage() : e.getClass().getSimpleName();
                    errors.add("Patch timeout for " + (edit.path() != null ? edit.path() : "unknown") + ": " + exMsg);
                    toolResults.add(Map.of("toolCallId", toolCallId, "success", false, "path", edit.path() != null ? edit.path() : "", "error", exMsg));
                }
            }
        }

        return new IndividualResult(toolResults, errors, appliedCount, failedCount);
    }

    private record IndividualResult(
            List<Map<String, Object>> toolResults,
            List<String> errors,
            int appliedCount,
            int failedCount) {}

}