package io.codepilot.plugin.settings

import com.intellij.credentialStore.CredentialAttributes
import com.intellij.credentialStore.Credentials
import com.intellij.ide.passwordSafe.PasswordSafe
import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.util.xmlb.XmlSerializerUtil
import java.nio.file.Path
import java.util.UUID

/**
 * Persistent CodePilot settings.
 *
 * Sensitive material (JWT, refresh token, deviceSecret) lives in IntelliJ's [PasswordSafe]; the
 * non-sensitive bits live in this XML state.
 */
@State(
    name = "io.codepilot.settings",
    storages = [Storage("codePilot.xml")],
)
@Service(Service.Level.APP)
class CodePilotSettings : PersistentStateComponent<CodePilotSettings.State> {
    data class State(
        // prd
        // var backendBaseUrl: String = "https://api.codepilot.local",
        // dev
        var backendBaseUrl: String = "http://localhost:8080",
        var deviceId: String = UUID.randomUUID().toString(),
        /** WebUI language: {@code en} or {@code zh} (see [LocaleHelper]). */
        var preferredLocale: String = LocaleHelper.EN,
        var sessionRoot: String = defaultSessionRoot(),
        var updateChannel: String = "stable",
        var contextBudgetTokens: Int = 24_000,
        var keepRecentMessages: Int = 6,
        var autoApplyLowRiskPatches: Boolean = false,
        /** ★ P0-03 Hunk Apply: when true, fs.write/create/replace go through PatchStaging
         *  so the WebUI can show per-hunk accept/reject before committing to disk. */
        /** When false (default), patches go through IDE diff / direct write instead of WebUI staging. */
        var stageBeforeApply: Boolean = false,
        var allowDevSso: Boolean = false,
        /** Dev token for bypassing JWT auth in development builds. Empty in production. */
        var devToken: String = "",
        /** ★ Privacy Mode: when true, no code/text is sent to the cloud; local-only. */
        var privacyMode: Boolean = false,
        /** ★ Local encryption for stored sessions when privacyMode is on. */
        var localEncryption: Boolean = false,
        /** ★ Anonymous telemetry mode: sends usage stats without PII. */
        var anonymousMode: Boolean = false,
        /** Conversation mode: "chat" or "agent" */
        var conversationMode: String = "chat",
        var registries: List<RegistryEntry> =
            listOf(
                RegistryEntry("Official", "https://marketplace.codepilot.io", ""),
            ),
    )

    private var state: State = State()

    override fun getState(): State = state

    @Volatile
    private var bundledDevLoginUi: Boolean? = null

    override fun loadState(state: State) {
        XmlSerializerUtil.copyBean(state, this.state)
        val bundled = loadBundledBuildProperties()
        if (this.state.devToken.isEmpty()) {
            this.state.devToken = bundled.devToken
        }
        bundledDevLoginUi = bundled.devLoginUi
    }

    /** Whether the WebUI may show the dev sign-in form (controlled at plugin build time). */
    fun isDevLoginUiEnabled(): Boolean = bundledDevLoginUi ?: loadBundledBuildProperties().devLoginUi

    private data class BundledBuildProperties(
        val devToken: String,
        val devLoginUi: Boolean,
    )

    /** Build-time flags from `codepilot-dev.properties` (generated by Gradle). */
    private fun loadBundledBuildProperties(): BundledBuildProperties {
        val log = com.intellij.openapi.diagnostic.Logger.getInstance("CodePilotSettings")
        try {
            val stream = javaClass.getResourceAsStream("/codepilot-dev.properties")
            if (stream != null) {
                val props = java.util.Properties()
                stream.use { props.load(it) }
                val token = props.getProperty("devToken", "").trim()
                val devLoginUi = props.getProperty("devLoginEnabled", "true").trim().lowercase() != "false"
                if (token.isNotEmpty()) {
                    log.info("[Settings] devToken loaded from bundled properties (length=${token.length})")
                }
                return BundledBuildProperties(token, devLoginUi)
            }
        } catch (e: Exception) {
            log.warn("[Settings] Failed to read codepilot-dev.properties", e)
        }
        val envToken = System.getenv("CODEPILOT_DEV_TOKEN")?.trim().orEmpty()
        val envDevLoginUi = System.getenv("CODEPILOT_DEV_LOGIN_UI")?.trim()?.lowercase() != "false"
        return BundledBuildProperties(envToken, envDevLoginUi)
    }

    fun update(mutator: (State) -> Unit) {
        mutator(state)
    }

    fun sessionRootPath(): Path = Path.of(state.sessionRoot)

    /** Read the access token from the password safe. */
    fun accessToken(): String? = read(CredAttr.JWT)

    fun setAccessToken(token: String?) = write(CredAttr.JWT, token)

    fun refreshToken(): String? = read(CredAttr.REFRESH)

    fun setRefreshToken(token: String?) = write(CredAttr.REFRESH, token)

    fun deviceSecret(): String? = read(CredAttr.DEVICE_SECRET)

    fun setDeviceSecret(secret: String?) = write(CredAttr.DEVICE_SECRET, secret)

    private fun read(attr: CredentialAttributes): String? = PasswordSafe.instance.getPassword(attr)

    private fun write(
        attr: CredentialAttributes,
        value: String?,
    ) {
        if (value == null) {
            PasswordSafe.instance.set(attr, null)
        } else {
            PasswordSafe.instance.set(attr, Credentials("codepilot", value))
        }
    }

    private object CredAttr {
        val JWT = CredentialAttributes("io.codepilot.jwt")
        val REFRESH = CredentialAttributes("io.codepilot.refresh")
        val DEVICE_SECRET = CredentialAttributes("io.codepilot.device-secret")
    }

    companion object {
        fun defaultSessionRoot(): String = Path.of(System.getProperty("user.home"), ".codePilot", "sessions").toString()

        @JvmStatic fun getInstance(): CodePilotSettings =
            com.intellij.openapi.components
                .service()
    }
}
