{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-context",
    "version": "1.41.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opentelemetry-context-1.41.0.jar",
          "url": "opentelemetry-context-1.41.0.jar",
          "size": 47252,
          "sha512": "d08d73d65d1fb8c1efa0a0c5dc0891dfafc52f3166603790f8842702de6b527f3103e41cee6418aaa90e7124a8ba61fac7cb0c8f64158d569eab38f4ae8a3126",
          "sha256": "5e3432a4464a432abfdab73be7142e516d25a84aa8426fce1192ffb0532faa35",
          "sha1": "3d7cf15ef425053e24e825160ca7b4ac08d721aa",
          "md5": "67307696010392cc06fae0d4024487b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-context-1.41.0.jar",
          "url": "opentelemetry-context-1.41.0.jar",
          "size": 47252,
          "sha512": "d08d73d65d1fb8c1efa0a0c5dc0891dfafc52f3166603790f8842702de6b527f3103e41cee6418aaa90e7124a8ba61fac7cb0c8f64158d569eab38f4ae8a3126",
          "sha256": "5e3432a4464a432abfdab73be7142e516d25a84aa8426fce1192ffb0532faa35",
          "sha1": "3d7cf15ef425053e24e825160ca7b4ac08d721aa",
          "md5": "67307696010392cc06fae0d4024487b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-context-1.41.0-javadoc.jar",
          "url": "opentelemetry-context-1.41.0-javadoc.jar",
          "size": 120393,
          "sha512": "d6892dc17481c1b3abbd1d9e1e1d85aa50690cf12d621cf675449647b64a3963a9104d3179387918c0cd871c1143227fe42a717e5b4f24d3cd5829754c48678f",
          "sha256": "7cc6c9ec7e94408839fc323284b96715e0481e9f3b8698ef8960c1f44b0541ea",
          "sha1": "ed833ed1cd11cb896c27ee9bc375865e49754ec3",
          "md5": "0f69aab893af7dc9a7d863f2070cb916"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-context-1.41.0-sources.jar",
          "url": "opentelemetry-context-1.41.0-sources.jar",
          "size": 37339,
          "sha512": "cfd16f8ae65e4aa0147d6a28f77f7a39882b17f8f39d653e22f20db9febd259b616b8c9b9d305ed3cbc639aa72af4cd61b857279ba95a642a58caf56b952718e",
          "sha256": "476565b58af8b59cd41325003f1fc3fb791116c509765974f04b3be8a121bb10",
          "sha1": "83908d94dcbd7293811e6714b59f2cbf02d06773",
          "md5": "b1d7a5944d8c36750da34936588d75a8"
        }
      ]
    }
  ]
}
