package io.codepilot.plugin.export

import com.fasterxml.jackson.databind.ObjectMapper
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import io.codepilot.plugin.session.SessionStore
import java.nio.file.Files
import java.nio.file.Path

@Service(Service.Level.PROJECT)
class ExportService(private val project: Project) {
    enum class Format { MARKDOWN, PR_DESCRIPTION, JSON }

    private val mapper = ObjectMapper()
    private val sessionStore = SessionStore.getInstance()
    private val workspaceHash = (project.basePath ?: project.name).hashCode().toString(16)

    fun export(sessionId: String, format: Format, includeTools: Boolean = true): String {
        val handle = sessionStore.resolve(workspaceHash, sessionId) ?: error("session not found: $sessionId")
        val messages = sessionStore.readMessages(handle)
        val steps = sessionStore.readSteps(handle)
        return when (format) {
            Format.JSON -> mapper.writerWithDefaultPrettyPrinter().writeValueAsString(
                mapOf("meta" to handle.meta, "messages" to messages, "steps" to steps),
            )
            Format.PR_DESCRIPTION -> renderPr(handle.meta.title ?: "CodePilot changes", messages, steps)
            Format.MARKDOWN -> renderMarkdown(handle.meta.title ?: "CodePilot session", handle.meta.id, messages, if (includeTools) steps else emptyList())
        }
    }

    fun save(sessionId: String, format: Format, target: String, includeTools: Boolean = true): Map<String, Any?> {
        val path = Path.of(target)
        path.parent?.let { Files.createDirectories(it) }
        Files.writeString(path, export(sessionId, format, includeTools))
        return mapOf("ok" to true, "path" to path.toString())
    }

    private fun renderMarkdown(
        title: String,
        sessionId: String,
        messages: List<Map<String, Any>>,
        steps: List<Map<String, Any>>,
    ): String = buildString {
        appendLine("# CodePilot session: $title")
        appendLine()
        appendLine("> Session: `$sessionId`")
        appendLine("> Workspace: `${project.basePath ?: project.name}`")
        appendLine()
        messages.forEachIndexed { idx, msg ->
            appendLine("## ${idx + 1}. ${msg["role"] ?: "message"}")
            appendLine()
            appendLine(msg["content"]?.toString() ?: "")
            val refs = msg["contextRefs"]
            if (refs != null) {
                appendLine()
                appendLine("Context: `$refs`")
            }
            appendLine()
        }
        if (steps.isNotEmpty()) {
            appendLine("## Tool / Step Records")
            appendLine()
            steps.forEach { step ->
                appendLine("```json")
                appendLine(mapper.writeValueAsString(step))
                appendLine("```")
                appendLine()
            }
        }
    }

    private fun renderPr(
        title: String,
        messages: List<Map<String, Any>>,
        steps: List<Map<String, Any>>,
    ): String = buildString {
        val userGoals = messages.filter { it["role"] == "user" }.takeLast(5).mapNotNull { it["content"]?.toString()?.take(120) }
        val changedTools = steps.mapNotNull { it["toolName"]?.toString() }.distinct()
        appendLine("## Summary")
        if (userGoals.isEmpty()) {
            appendLine("- $title")
        } else {
            userGoals.forEach { appendLine("- $it") }
        }
        appendLine()
        appendLine("## Changes")
        if (changedTools.isEmpty()) appendLine("- Conversation-only changes; inspect exported session for details.")
        else changedTools.forEach { appendLine("- Used `$it` during implementation.") }
        appendLine()
        appendLine("## Test Plan")
        appendLine("- [ ] Review generated changes")
        appendLine("- [ ] Run relevant project tests")
        appendLine()
        appendLine("---")
        appendLine("Generated by CodePilot from session export.")
    }

    companion object {
        fun getInstance(project: Project): ExportService = project.service()
    }
}
