{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-lib-extra",
    "version": "2.45.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "2.45.0"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-2.45.0.jar",
          "url": "spotless-lib-extra-2.45.0.jar",
          "size": 79604,
          "sha512": "4e4889a8c3226a3a89942ec8df4a160292120ac94d78d25f9532c7b7218202f71fab04a39c7d804b16f579e97c759d1f5d5dc57dd6f82f668380ca534365612c",
          "sha256": "602cbbcd3828ee9cfb2e30a7f9b30335c6927130771414d4cdd294d21fe5cb67",
          "sha1": "3d98a914d2692f17ea47eae82fbac8a1b7b30640",
          "md5": "30e3777b7606362c663ae16d5ddd9a78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.diffplug.durian",
          "module": "durian-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-collect",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.7.0.202309050840-r"
          }
        },
        {
          "group": "com.googlecode.concurrent-trees",
          "module": "concurrent-trees",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "dev.equo.ide",
          "module": "solstice",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "2.45.0"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-2.45.0.jar",
          "url": "spotless-lib-extra-2.45.0.jar",
          "size": 79604,
          "sha512": "4e4889a8c3226a3a89942ec8df4a160292120ac94d78d25f9532c7b7218202f71fab04a39c7d804b16f579e97c759d1f5d5dc57dd6f82f668380ca534365612c",
          "sha256": "602cbbcd3828ee9cfb2e30a7f9b30335c6927130771414d4cdd294d21fe5cb67",
          "sha1": "3d98a914d2692f17ea47eae82fbac8a1b7b30640",
          "md5": "30e3777b7606362c663ae16d5ddd9a78"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-2.45.0-javadoc.jar",
          "url": "spotless-lib-extra-2.45.0-javadoc.jar",
          "size": 377299,
          "sha512": "95943313498d2e3f019cc4e7b99e4c34d206e50c8a6b02a305a665959b2a3dbd9f40434ccf6040f720cd3188015178a0f86349166b3cfa8574c45277b83b16a8",
          "sha256": "336291f0771f49dab09fb517000464e42539f0b912eb348643adfaeb52d0c1f9",
          "sha1": "4c4eea59bd92c2b2de45dc75f2cd425f6f4ec17f",
          "md5": "323094ee641f0ea4ceba0a3839066f2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-2.45.0-sources.jar",
          "url": "spotless-lib-extra-2.45.0-sources.jar",
          "size": 39534,
          "sha512": "4975aa5227192fc5937aa7b8f2989bbde0836336af78b05562229e8f7144a969dd8178364ecb3fc90fc3136c60f247dc5f6504f6866f2bba1050e7f35493b7f0",
          "sha256": "372071793a0cbf4a341b15138a55cc17b9b174c0d95b9593203757bca26f4fed",
          "sha1": "8fb39bfa9fab4c6d8f1db93f7bd0d75305a30fdd",
          "md5": "810ce151db97c8172d3f8b0e8af4d68e"
        }
      ]
    }
  ]
}
