{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-api",
    "version": "1.41.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-context",
          "version": {
            "requires": "1.41.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-api-1.41.0.jar",
          "url": "opentelemetry-api-1.41.0.jar",
          "size": 142638,
          "sha512": "9da867702ff016cc60311c4e76543bc3ba8eebb641b208ef53f0f60207ea320ee8bdd4d5b90e27104894c024a1aac9bfa1561ce328ed73abd8223c0096fe79f4",
          "sha256": "9336668f388de68a0a2c3e114154febd29db19a7644f27c4eba548f5de852258",
          "sha1": "ec5ad3b420c9fba4b340e85a3199fd0f2accd023",
          "md5": "ff5395c2524b24717ead3f11404d316f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-context",
          "version": {
            "requires": "1.41.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-api-1.41.0.jar",
          "url": "opentelemetry-api-1.41.0.jar",
          "size": 142638,
          "sha512": "9da867702ff016cc60311c4e76543bc3ba8eebb641b208ef53f0f60207ea320ee8bdd4d5b90e27104894c024a1aac9bfa1561ce328ed73abd8223c0096fe79f4",
          "sha256": "9336668f388de68a0a2c3e114154febd29db19a7644f27c4eba548f5de852258",
          "sha1": "ec5ad3b420c9fba4b340e85a3199fd0f2accd023",
          "md5": "ff5395c2524b24717ead3f11404d316f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-api-1.41.0-javadoc.jar",
          "url": "opentelemetry-api-1.41.0-javadoc.jar",
          "size": 296637,
          "sha512": "49b4a7c4a4ed86ec51cee84900e1a6f74a99d1c960690d9aec34c3f8fbaac235df5fcf8a4fe6f1c3a4957582ef999cef1ed74b1ba047eb2503d3284116f27eb9",
          "sha256": "14cee1552ea60dd2e97a7c6b13127e2f5d77ad8ac458f3f9131af9c6ed48c9b9",
          "sha1": "9f8b8bf3ce059227053709259a1bf20cc9498840",
          "md5": "83a46bbb3c57f9662f17c67d37cbdaae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-api-1.41.0-sources.jar",
          "url": "opentelemetry-api-1.41.0-sources.jar",
          "size": 111993,
          "sha512": "a1d2f368989cfd2a5e8fb64d2e9414d787817edbc7e9c741e6a3d0fc1efffb5ad13ff242121baf08000bf7277c20aa161c68fbb1ea9cb3b90f0ca3c3ef89875c",
          "sha256": "7a29795475a8dbe670afd124a64e7dd94f129eecb6c529ecaa47aaa01ba2c018",
          "sha1": "2e2b296308f4c9ab564ad66dc9b56f0ee8573f84",
          "md5": "4f691ad84850dea397d4d418ff2a9324"
        }
      ]
    }
  ]
}
