apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codepilot.fullname" . }}-env
  labels: {{ include "codepilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}