{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-sdk",
    "version": "1.41.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.41.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-common",
          "version": {
            "requires": "1.41.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-trace",
          "version": {
            "requires": "1.41.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-metrics",
          "version": {
            "requires": "1.41.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.41.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-1.41.0.jar",
          "url": "opentelemetry-sdk-1.41.0.jar",
          "size": 6769,
          "sha512": "98ba2baa868576419b34758705ffea2dc80e4cf63e49d810108ea303d21158624a8a26e8f1d26c059d74d2cd9f2260f5a529790dba56b5e4d0c7309ebca516cf",
          "sha256": "1e20916ea9b76b85aec3ad1c78170e0cd59556f3ae120ec4fdea256a87cb3d91",
          "sha1": "c740e8f7d0d914d6acd310ac53901bb8753c6e8d",
          "md5": "fd59d931561e82fdcd2ac79add458feb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.41.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-common",
          "version": {
            "requires": "1.41.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-trace",
          "version": {
            "requires": "1.41.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-metrics",
          "version": {
            "requires": "1.41.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.41.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-1.41.0.jar",
          "url": "opentelemetry-sdk-1.41.0.jar",
          "size": 6769,
          "sha512": "98ba2baa868576419b34758705ffea2dc80e4cf63e49d810108ea303d21158624a8a26e8f1d26c059d74d2cd9f2260f5a529790dba56b5e4d0c7309ebca516cf",
          "sha256": "1e20916ea9b76b85aec3ad1c78170e0cd59556f3ae120ec4fdea256a87cb3d91",
          "sha1": "c740e8f7d0d914d6acd310ac53901bb8753c6e8d",
          "md5": "fd59d931561e82fdcd2ac79add458feb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-1.41.0-javadoc.jar",
          "url": "opentelemetry-sdk-1.41.0-javadoc.jar",
          "size": 86117,
          "sha512": "cb727b670ade97b99a9219f62f5c30a2953487bf149eeadf01cfeec64b6fc26293a715c23af72bdd97b98114317da10e1077df82f422e7f64210ddc340f584df",
          "sha256": "bdf0c2ea7040e7c0732cd057451a34407d46436bbe1c9d6f2a67f1cde239e49a",
          "sha1": "e99520ae30980fa2add252ed1b971d67c4846b13",
          "md5": "a8ab8a0d66cc9b4c79f9eb359f07da27"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-1.41.0-sources.jar",
          "url": "opentelemetry-sdk-1.41.0-sources.jar",
          "size": 3894,
          "sha512": "b6c4655e51d88ae60cc79ea5b2fa946ba39dff0f4487c5220e136aee7f6ba0077800c0eb7f59c138e17d95c2db31841b662b2563eb37fcfab74370b4abf4e99e",
          "sha256": "dcc4ea7543d910af2d00566198fe2a0785a06868db0fd818fb74112b8246aea6",
          "sha1": "1743943219281f328b770cb21a761939f29ad460",
          "md5": "44c334a0399aeaf85e4be05bb12fb95b"
        }
      ]
    }
  ]
}
