{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-jsonSchema",
    "version": "2.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "1.1.0.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jsonSchema-2.17.2.jar",
          "url": "jackson-module-jsonSchema-2.17.2.jar",
          "size": 79472,
          "sha512": "439144579cd766a216f4f72c363a9ecf1b448b4aa075a225fc3fabc775c114324ae7c3851d4d118f4e7ffc6c9a14c26b845338df5d95fb4cb9e4708b7bb5cbb5",
          "sha256": "d07d211c94d949c918bc9b79f84e30b2284c6c4e9876721059495a2831886743",
          "sha1": "52ab6a587f9d8c4613d71f250c5e1d347871a0f8",
          "md5": "c0584f734c4785611b56052db7e0d50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "1.1.0.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jsonSchema-2.17.2.jar",
          "url": "jackson-module-jsonSchema-2.17.2.jar",
          "size": 79472,
          "sha512": "439144579cd766a216f4f72c363a9ecf1b448b4aa075a225fc3fabc775c114324ae7c3851d4d118f4e7ffc6c9a14c26b845338df5d95fb4cb9e4708b7bb5cbb5",
          "sha256": "d07d211c94d949c918bc9b79f84e30b2284c6c4e9876721059495a2831886743",
          "sha1": "52ab6a587f9d8c4613d71f250c5e1d347871a0f8",
          "md5": "c0584f734c4785611b56052db7e0d50"
        }
      ]
    }
  ]
}
